// Static game data and balance knobs.
// Core rules: work / train / fight, energy + food, damage formula, military ranks,
// resource bonuses, campaigns and politics, compressed so one real-time session
// feels like several days of a classic browser strategy game.

import { EU_COUNTRIES } from './europe.js';

export const SAVE_VERSION = 2; // v2: real Europe map (v1 saves used the fictional hex map)
export const GAME_TITLE = 'Republic Rising';

export const CONFIG = {
  energyRegenMs: 5000, // +1 usable energy every 5 s
  reserveRegenMs: 1000, // +1 food reserve ("potential energy") every second
  energyCap: 400,
  offlineCapMs: 8 * 3600 * 1000,
  workEnergy: 10,
  trainEnergy: 10,
  perfectWorkBonus: 0.2, // a shift timed in the gauge's gold zone pays +20%…
  perfectTrainBonus: 0.25, // …and a perfect training session gives +25% strength
  shotEnergy: 1,
  enemyShotEnergy: 4,
  battleMs: 5 * 60 * 1000, // every battle is a single 5-minute round
  aiTickMs: 20000,
  maxAiCampaigns: 40,
  aiWarChance: 0.15,
  regionsPerFront: 4, // a nation can attack on 1 + regions/4 fronts at once…
  maxFronts: 14, // …up to this many
  maxPlayerFronts: 5, // battles of the player's own country at the same time
  rwChance: 0.004, // per occupied region and world tick (a fifth of it once the nation is wiped out)
  defenseBonus: 1.15,
  lostCapitalMorale: 0.7, // base strength of a nation whose capital is occupied
  newEraDelayMs: 10 * 60 * 1000, // after one nation rules all of Europe, every nation rises again
  surrenderAllAt: 5, // a nation with this many regions or fewer surrenders entirely when its capital falls
  electionEveryMs: 10 * 60 * 1000,
  articleCooldownMs: 3 * 60 * 1000,
  marketShiftMs: 60000,
  sellRatio: 0.8,
  goldBuyPrice: 120,
  goldSellPrice: 80,
  companyStorageMinutes: 180,
  midgameCooldownMs: 3 * 60 * 1000,
  doubleCollectCooldownMs: 5 * 60 * 1000,
  freeGoldCooldownMs: 10 * 60 * 1000,
  houseDurationMs: 4 * 3600 * 1000, // a house lasts 4 hours of real time
};

// Real European countries and regions; geometry is generated by scripts/build-map.mjs.
const darken = (hex, f = 0.45) => '#' + [1, 3, 5].map((i) => Math.round(parseInt(hex.slice(i, i + 2), 16) * f).toString(16).padStart(2, '0')).join('');
export const COUNTRIES = EU_COUNTRIES.map((c) => ({ ...c, dark: darken(c.color) }));

export const countryById = (id) => COUNTRIES.find((c) => c.id === id);

export const RESOURCES = {
  grain: { kind: 'food', icon: '🌾', name: 'Grain' },
  fish: { kind: 'food', icon: '🐟', name: 'Fish' },
  fruit: { kind: 'food', icon: '🍎', name: 'Fruits' },
  cattle: { kind: 'food', icon: '🐄', name: 'Cattle' },
  deer: { kind: 'food', icon: '🦌', name: 'Deer' },
  iron: { kind: 'weapon', icon: '⛓️', name: 'Iron' },
  oil: { kind: 'weapon', icon: '🛢️', name: 'Oil' },
  saltpeter: { kind: 'weapon', icon: '🧪', name: 'Saltpeter' },
  rubber: { kind: 'weapon', icon: '🌳', name: 'Rubber' },
  aluminum: { kind: 'weapon', icon: '🔩', name: 'Aluminum' },
};
export const FOOD_RES = Object.keys(RESOURCES).filter((k) => RESOURCES[k].kind === 'food');
export const WEAPON_RES = Object.keys(RESOURCES).filter((k) => RESOURCES[k].kind === 'weapon');
export const RESOURCE_BONUS = 0.2; // +20% production per distinct resource

// Military ranks. Index = rank level used in the damage formula.
const RANK_BASE = ['Private', 'Corporal', 'Sergeant', 'Lieutenant', 'Captain', 'Major', 'Commander',
  'Lt Colonel', 'Colonel', 'General', 'Field Marshal', 'Supreme Marshal', 'National Force',
  'World Class Force', 'Legendary Force', 'God of War', 'Titan'];
export const RANKS = ['Recruit', ...RANK_BASE.flatMap((b) => [b, b + ' *', b + ' **', b + ' ***'])];
export const rankThreshold = (i) => (i <= 0 ? 0 : Math.round(25 * Math.pow(i, 2.3)));
export function rankIndexOf(rp) {
  let i = 0;
  while (i + 1 < RANKS.length && rp >= rankThreshold(i + 1)) i++;
  return i;
}
export const xpToNextLevel = (lvl) => 30 + lvl * 20;

// Food quality -> energy restored. Weapon quality -> firepower (higher quality, more firepower).
export const FOOD_ENERGY = [0, 10, 20, 30, 40, 50];
export const WEAPON_FP = [0, 20, 40, 60, 80, 100];

export const MARKET = {
  foodRaw: { name: 'Food raw', icon: '🌾', base: 0.02 },
  weaponRaw: { name: 'Weapon raw', icon: '⛓️', base: 0.03 },
  food1: { name: 'Food Q1', icon: '🍞', base: 0.3 },
  food2: { name: 'Food Q2', icon: '🍞', base: 0.6 },
  food3: { name: 'Food Q3', icon: '🍞', base: 0.9 },
  food4: { name: 'Food Q4', icon: '🍞', base: 1.2 },
  food5: { name: 'Food Q5', icon: '🍞', base: 1.5 },
  weapon1: { name: 'Weapon Q1', icon: '🔫', base: 0.2 },
  weapon2: { name: 'Weapon Q2', icon: '🔫', base: 0.4 },
  weapon3: { name: 'Weapon Q3', icon: '🔫', base: 0.6 },
  weapon4: { name: 'Weapon Q4', icon: '🔫', base: 0.8 },
  weapon5: { name: 'Weapon Q5', icon: '🔫', base: 1.0 },
  houseRaw: { name: 'Building materials', icon: '🧱', base: 0.04 },
  house1: { name: 'Hut (Q1)', icon: '🛖', base: 40 },
  house2: { name: 'Cottage (Q2)', icon: '🏠', base: 100 },
  house3: { name: 'Townhouse (Q3)', icon: '🏡', base: 220 },
  house4: { name: 'Villa (Q4)', icon: '🏘️', base: 450 },
  house5: { name: 'Mansion (Q5)', icon: '🏰', base: 900 },
};

export const RAW_ICON = { foodRaw: '🌾', weaponRaw: '⛓️', houseRaw: '🧱' };

// Houses: each quality you live in adds max energy and faster energy regeneration.
// Different qualities stack; a house wears out after CONFIG.houseDurationMs.
export const HOUSES = [
  null,
  { name: 'Hut', icon: '🛖', energy: 20, regen: 0.1 },
  { name: 'Cottage', icon: '🏠', energy: 40, regen: 0.2 },
  { name: 'Townhouse', icon: '🏡', energy: 60, regen: 0.3 },
  { name: 'Villa', icon: '🏘️', energy: 80, regen: 0.4 },
  { name: 'Mansion', icon: '🏰', energy: 100, regen: 0.5 },
];

export const GOLD_SHOP = {
  bazooka: { name: 'Bazooka', icon: '🚀', gold: 2, desc: 'One massive blast that hits every enemy on screen.' },
  energyBar: { name: 'Energy Bar', icon: '⚡', gold: 1, desc: '+50 energy instantly (ignores food reserve).' },
};

export const COMPANY_TYPES = {
  farm: { name: 'Farm', icon: '🌾', kind: 'raw', output: 'foodRaw', res: 'food', rate: 60, cost: 150,
    desc: 'Produces food raw materials. Boosted by food resources your country owns.' },
  mine: { name: 'Mine', icon: '⛏️', kind: 'raw', output: 'weaponRaw', res: 'weapon', rate: 60, cost: 150,
    desc: 'Produces weapon raw materials. Boosted by weapon resources your country owns.' },
  bakery: { name: 'Bakery', icon: '🍞', kind: 'factory', output: 'food', input: 'foodRaw', rate: 12, cost: 400,
    desc: 'Turns food raw into food. Each unit needs Q raw.' },
  armory: { name: 'Arms Factory', icon: '🔫', kind: 'factory', output: 'weapon', input: 'weaponRaw', rate: 25, cost: 600,
    desc: 'Turns weapon raw into weapons. Each unit needs Q raw.' },
  quarry: { name: 'Quarry', icon: '🪨', kind: 'raw', output: 'houseRaw', res: null, rate: 60, cost: 250,
    desc: 'Produces building materials for houses.' },
  construction: { name: 'Construction Co.', icon: '🏗️', kind: 'factory', output: 'house', input: 'houseRaw', rate: 0.1, rawMult: 100, cost: 1200,
    desc: 'Builds houses. Each house needs 100 × Q building materials.' },
};

// Training grounds: each facility has a quality from Q1 to Q5 (0 = not built).
// `gain` is the Q1 strength per training; `cost[q-1]` is the gold price to reach quality q.
export const FACILITIES = [
  { id: 'weights', name: 'Weights Room', icon: '🏋️', gain: 5, cost: [0, 3, 6, 12, 25] },
  { id: 'climbing', name: 'Climbing Center', icon: '🧗', gain: 2.5, cost: [5, 5, 10, 20, 35] },
  { id: 'shooting', name: 'Shooting Range', icon: '🎯', gain: 5, cost: [15, 10, 20, 35, 60] },
  { id: 'special', name: 'Special Forces Center', icon: '🪖', gain: 10, cost: [40, 20, 40, 70, 120] },
];
export const FACILITY_MAX_Q = 5;
export const FACILITY_QUALITY_MULT = [0, 1, 1.25, 1.5, 1.8, 2.2];
// The k-th Super Soldier medal needs 250 * k^1.6 strength gained in total (250, 758, 1450, ...).
export const superSoldierThreshold = (k) => Math.round(250 * Math.pow(k, 1.6));

export const POLICIES = {
  production: { name: 'Industrial Plan', desc: '+15% company production', mult: 1.15 },
  damage: { name: 'Military Doctrine', desc: '+10% damage for all citizens', mult: 1.1 },
  salary: { name: 'Minimum Wage Act', desc: '+20% salaries', mult: 1.2 },
};

export const MEDALS = {
  hardWorker: { name: 'Hard Worker', icon: '🛠️', desc: 'Work 30 times', gold: 5 },
  superSoldier: { name: 'Super Soldier', icon: '💪', desc: 'Strength milestones (250, 758, 1450…)', gold: 5 },
  battleHero: { name: 'Battle Hero', icon: '🎖️', desc: 'Top damage of a whole battle', gold: 3 },
  campaignHero: { name: 'Campaign Hero', icon: '🏆', desc: 'Deal a quarter of your side\'s damage in a won battle', gold: 5 },
  truePatriot: { name: 'True Patriot', icon: '🛡️', desc: 'Deal 20,000 damage for your country', gold: 5 },
  resistanceHero: { name: 'Resistance Hero', icon: '✊', desc: 'Win a resistance war you fought in', gold: 5 },
  congressMember: { name: 'Congress Member', icon: '🏛️', desc: 'Get elected to Congress', gold: 5 },
  president: { name: 'Country President', icon: '👑', desc: 'Get elected President', gold: 5 },
  mediaMogul: { name: 'Media Mogul', icon: '📰', desc: 'Reach newspaper subscriber milestones', gold: 5 },
  tycoon: { name: 'Tycoon', icon: '🏭', desc: 'Own 5 companies', gold: 5 },
};
export const MEDIA_MILESTONES = [100, 500, 1000, 2500, 5000, 10000];
export const PATRIOT_STEP = 20000;

// Tutorial chain of starter missions.
export const TUTORIAL = [
  { text: 'Work at your job to earn money', ev: 'work', n: 1, reward: { money: 20 } },
  { text: 'Train to increase your strength', ev: 'train', n: 1, reward: { gold: 1 } },
  { text: 'Open the War tab and defeat 10 enemies', ev: 'kill', n: 10, reward: { weapon1: 100 }, tab: 'war' },
  { text: 'Eat food to refill energy from your reserve', ev: 'eat', n: 1, reward: { food2: 10 } },
  { text: 'Buy food or weapons on the Market', ev: 'buy', n: 1, reward: { weapon2: 50 }, tab: 'market' },
  { text: 'Meet your fellow citizens in the Citizens tab rankings', ev: 'rankView', n: 1, reward: { money: 30 }, tab: 'people' },
  { text: 'Fight in a battle your country wins', ev: 'roundWin', n: 1, reward: { gold: 2 }, tab: 'war' },
  { text: 'Build a Farm in the Economy tab', cond: (s) => s.companies.some((c) => c.type === 'farm'), reward: { money: 100 }, tab: 'economy' },
  { text: 'Build a Bakery to turn raw materials into food', cond: (s) => s.companies.some((c) => c.type === 'bakery'), reward: { gold: 2 }, tab: 'economy' },
  { text: 'Collect production from your companies', ev: 'collect', n: 1, reward: { money: 50 }, tab: 'economy' },
  { text: 'Post a sell offer on the Market (citizens will buy it)', ev: 'post', n: 1, reward: { gold: 1 }, tab: 'market' },
  { text: 'Buy a house on the Market and move in', ev: 'moveIn', n: 1, reward: { gold: 2 }, tab: 'market' },
  { text: 'Reach level 3 and join a political party', cond: (s) => s.politics.party, reward: { gold: 1 }, tab: 'politics' },
  { text: 'Reach level 5', cond: (s) => s.player.level >= 5, reward: { gold: 5 } },
  { text: 'Found a newspaper and publish an article', ev: 'article', n: 1, reward: { gold: 3 }, tab: 'politics' },
  { text: 'Help your country conquer a region', ev: 'conquest', n: 1, reward: { gold: 5, bazooka: 2 }, tab: 'war' },
];

export const DAILY_POOL = [
  { id: 'work', text: 'Work 5 times', ev: 'work', n: 5 },
  { id: 'train', text: 'Train 5 times', ev: 'train', n: 5 },
  { id: 'kill', text: 'Defeat 150 enemies', ev: 'kill', n: 150 },
  { id: 'round', text: 'Fight in 2 won battles', ev: 'roundWin', n: 2 },
  { id: 'collect', text: 'Collect production 3 times', ev: 'collect', n: 3 },
  { id: 'eat', text: 'Eat food 3 times', ev: 'eat', n: 3 },
  { id: 'head', text: 'Land 40 headshots', ev: 'headshot', n: 40 },
];
export const DAILY_COUNT = 4;
export const DAILY_REWARD_GOLD = 1;
export const DAILY_BONUS = { gold: 3, bazooka: 1 };

export const LOGIN_REWARDS = [
  { money: 100 },
  { food2: 20 },
  { gold: 2 },
  { weapon2: 200 },
  { gold: 3 },
  { bazooka: 3 },
  { gold: 8, food3: 30 },
];

export const PRESIDENT_NAMES = ['Aldric Stone', 'Mira Vance', 'Tomas Hale', 'Ines Korr', 'Viktor Lund',
  'Sela Marsh', 'Oren Blackwood', 'Lena Frost', 'Dario Quill', 'Nadia Rook', 'Felix Ward', 'Ysolde Grey'];
